#!/usr/bin/env python
import os
import sys

from methods import print_error

libname = "ai_provider"

# ---------------------------------------------------------------------------
# godot-cpp / SCons environment setup
# ---------------------------------------------------------------------------
localEnv = Environment(tools=["default"], PLATFORM="")

# Build profiles can be used to decrease compile times.
# You can either specify "disabled_classes", OR
# explicitly specify "enabled_classes" which disables all other classes.
# Modify the example file as needed and uncomment the line below or
# manually specify the build_profile parameter when running SCons.

# localEnv["build_profile"] = "build_profile.json"

customs = ["#custom.py"]
customs = [Dir(path).abspath for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("vendor/godot-cpp") and os.listdir("vendor/godot-cpp")):
    print_error("""vendor/godot-cpp is not available within this folder, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

# Use zig cc/c++ as the compiler for the extension as well, so the same
# toolchain is used throughout (avoids ABI mismatches on Linux).
env["CC"] = "zig cc"
env["CXX"] = "zig c++"
env["AR"] = "zig ar"
env["RANLIB"] = "zig ranlib"
env["RC"] = "zig rc"
env["ENV"]["ZIG_GLOBAL_CACHE_DIR"] = "/tmp/zig-cache"
env["ENV"]["ZIG_LOCAL_CACHE_DIR"] = ".zig-cache"
env["ENV"]["XDG_CACHE_HOME"] = "/tmp"

env = SConscript("vendor/godot-cpp/SConstruct", {"env": env, "customs": customs})

# ---------------------------------------------------------------------------
# Extension sources
# ---------------------------------------------------------------------------

LLAMA_SRC_DIR = Dir("vendor/llama.cpp").abspath
LLAMA_BUILD_DIR = Dir("build/llama.cpp").abspath

if not (
    os.path.isdir("vendor/json-schema-validator")
    and os.listdir("vendor/json-schema-validator")
):
    print_error("""vendor/json-schema-validator is not available within this folder.
Make sure the dependency is present under vendor/json-schema-validator before building.""")
    sys.exit(1)

env.Append(
    CPPPATH=[
        "src/",
        os.path.join(LLAMA_SRC_DIR, "include"),  # llama.h / llama-cpp.h
        os.path.join(LLAMA_SRC_DIR, "ggml", "include"),  # ggml.h and friends
        os.path.join(LLAMA_SRC_DIR, "common"),  # common.h
        os.path.join(LLAMA_SRC_DIR, "vendor"),
        Dir("vendor/json-schema-validator/src").abspath,
    ]
)

sources = Glob("src/*.cpp")

if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData(
            "src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml")
        )
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")


# ---------------------------------------------------------------------------
# llama.cpp static-library build via CMake
# ---------------------------------------------------------------------------


def get_lib_filename(lib_name, dirs):
    lib_prefix = env.subst("$LIBPREFIX")
    lib_suffix = env.subst("$LIBSUFFIX")
    return os.path.join(LLAMA_BUILD_DIR, *dirs, f"{lib_prefix}{lib_name}{lib_suffix}")


def get_cmake_toolchain():
    match env["platform"]:
        case "linux":
            return os.path.abspath("cmake/x86_64-linux-gnu.cmake")
        case "macos":
            return os.path.abspath("cmake/x86_64-macos-none.cmake")
        case "windows":
            return os.path.abspath("cmake/x86_64-windows-gnu.cmake")


llama_cpp_libs = [
    (["common"], "common"),
    (["src"], "llama"),
    (["ggml", "src"], "ggml"),
    (["ggml", "src"], "ggml-base"),
    (["ggml", "src"], "ggml-cpu"),
]


llama_cpp_targets = [
    get_lib_filename(lib_name, dirs) for dirs, lib_name in llama_cpp_libs
]

llama_cpp_lib = env.Command(
    target=llama_cpp_targets,
    source=os.path.join(LLAMA_SRC_DIR, "CMakeLists.txt"),
    action=[
        (
            f"cmake -S {LLAMA_SRC_DIR} -B {LLAMA_BUILD_DIR}"
            f" --toolchain {get_cmake_toolchain()}"
            " -DBUILD_SHARED_LIBS=OFF"
            " -DLLAMA_BUILD_TESTS=OFF"
            " -DLLAMA_BUILD_EXAMPLES=OFF"
            " -DLLAMA_BUILD_TOOLS=OFF"
            " -DLLAMA_BUILD_SERVER=OFF"
            " -DLLAMA_BUILD_COMMON=ON"
            " -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
            " -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
            " -DCMAKE_BUILD_TYPE=Release"
        ),
        f"cmake --build {LLAMA_BUILD_DIR}",
    ],
)

env.Append(LIBPATH=[os.path.dirname(target) for target in llama_cpp_targets])
env.Append(LIBS=[lib_name for _, lib_name in llama_cpp_libs])


# ---------------------------------------------------------------------------
# json-schema-validator static-library build via SCons
# ---------------------------------------------------------------------------

json_schema_validator_sources = Glob("vendor/json-schema-validator/src/*.cpp")

json_schema_validator_env = env.Clone()
json_schema_validator_env["CCFLAGS"] = [
    flag for flag in json_schema_validator_env["CCFLAGS"] if flag != "-fno-exceptions"
]
json_schema_validator_env.Append(CCFLAGS=["-fexceptions"])

json_schema_validator_lib = json_schema_validator_env.StaticLibrary(
    os.path.join("build", "json-schema-validator", "nlohmann_json_schema_validator"),
    source=json_schema_validator_sources,
)

env.Append(LIBPATH=[Dir("build/json-schema-validator").abspath])
env.Append(LIBS=["nlohmann_json_schema_validator"])


# ---------------------------------------------------------------------------
# Final shared library
# ---------------------------------------------------------------------------
# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = env["suffix"].replace(".dev", "").replace(".universal", "")

lib_filename = "{}{}{}{}".format(
    env.subst("$SHLIBPREFIX"), libname, suffix, env.subst("$SHLIBSUFFIX")
)

library = env.SharedLibrary(
    "bin/{}/{}".format(env["platform"], lib_filename),
    source=sources,
)

env.Depends(library, llama_cpp_lib)
env.Depends(library, json_schema_validator_lib)

default_args = [library]
Default(*default_args)
